# Generated by Django 4.2.5 on 2024-10-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_volunteer_labor_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="labor_hours",
            field=models.IntegerField(),
        ),
    ]
