# Generated by Django 4.2.5 on 2024-10-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_volunteer_labor_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="token",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="token_expiration",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="activitystatus",
            name="activity_status",
            field=models.CharField(
                choices=[
                    ("未开始", "未开始"),
                    ("招募中", "招募中"),
                    ("已招满", "已招满"),
                    ("进行中", "进行中"),
                    ("已结束", "已结束"),
                    ("已取消", "已取消"),
                ],
                max_length=50,
            ),
        ),
    ]
