# Generated by Django 4.2.5 on 2024-10-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_volunteer_token_volunteer_token_expiration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizer",
            name="token",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="organizer",
            name="token_expiration",
            field=models.DateTimeField(null=True),
        ),
    ]
